package com.mixonko.android.memorycardgame

const val IMAGE_VIEW_11_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_11_IS_VISIBLE"
const val IMAGE_VIEW_12_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_12_IS_VISIBLE"
const val IMAGE_VIEW_13_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_13_IS_VISIBLE"
const val IMAGE_VIEW_14_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_14_IS_VISIBLE"
const val IMAGE_VIEW_21_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_21_IS_VISIBLE"
const val IMAGE_VIEW_22_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_22_IS_VISIBLE"
const val IMAGE_VIEW_23_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_23_IS_VISIBLE"
const val IMAGE_VIEW_24_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_24_IS_VISIBLE"
const val IMAGE_VIEW_31_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_31_IS_VISIBLE"
const val IMAGE_VIEW_32_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_32_IS_VISIBLE"
const val IMAGE_VIEW_33_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_33_IS_VISIBLE"
const val IMAGE_VIEW_34_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_34_IS_VISIBLE"
const val IMAGE_VIEW_41_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_41_IS_VISIBLE"
const val IMAGE_VIEW_42_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_42_IS_VISIBLE"
const val IMAGE_VIEW_43_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_43_IS_VISIBLE"
const val IMAGE_VIEW_44_IS_VISIBLE = "com.mixonko.android.memorycardgame.IMAGE_VIEW_44_IS_VISIBLE"

const val FIRST_PLAYER_GLOBAL_POINTS = "com.mixonko.android.memorycardgame.FIRST_PLAYER_GLOBAL_POINTS"
const val SECOND_PLAYER_GLOBAL_POINTS = "com.mixonko.android.memorycardgame.SECOND_PLAYER_GLOBAL_POINTS"
const val FIRST_PLAYER_POINTS = "com.mixonko.android.memorycardgame.FIRST_PLAYER_POINTS"
const val SECOND_PLAYER_POINTS = "com.mixonko.android.memorycardgame.SECOND_PLAYER_POINTS"
const val ARRAY = "com.mixonko.android.memorycardgame.ARRAY"
const val TURN = "com.mixonko.android.memorycardgame.TURN"
const val APP_PREFERENCES = "com.mixonko.android.memorycardgame.APP_PREFERENCES"
const val LOAD_GAME = "com.mixonko.android.memorycardgame.LOAD_GAME"
const val CHECK_AND_GAME = "com.mixonko.android.memorycardgame.CHECK_AND_GAME"
